### ISSUE TITLE
How to make 32 frames?

### ISSUE THREAD

**Issue by didoll-john** [chaojie/ComfyUI-DynamiCrafter#7]
I set the frames to 32:
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 12.29 GiB
Requested               : 50.62 GiB
Device limit            : 23.68 GiB
Free (according to CUDA): 874.50 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

then set frames to 16:
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 11.02 GiB
Requested               : 25.31 GiB
Device limit            : 23.68 GiB
Free (according to CUDA): 10.50 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

set to 12:
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 10.72 GiB
Requested               : 18.98 GiB
Device limit            : 23.68 GiB
Free (according to CUDA): 10.50 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

**Comment by chaojie** [comment]
pip install xformers

**Comment by didoll-john** [comment]
There is xformers in my ComfyUI env, but no work.
I created a new env for DynamiCrafter(original), and it works.
Thanks anyway.
